import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/containers/navigation/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wobble",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // TODO: add navbar and footer to this page
  return (
    <html lang="en">
      <body className={`${inter.className} w-full flex flex-col min-h-screen`}>
        <Header />
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  );
}
